apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/danielm-codefresh/canary-rollout.git
    targetRevision: HEAD
  destination:
    name: daniel-dev
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
