apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: resources
    repoURL: git@github.com:danielm-codefresh/guestbook.git
    targetRevision: HEAD
  destination:
    name: daniel-dev
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
