apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: resources
    repoURL: https://github.com/danielm-codefresh/guestbook.git
    targetRevision: HEAD
  destination:
    name: in-clusters
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
