apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/danielm-codefresh/rollouts-demo.git
    targetRevision: HEAD
  destination:
    name: daniel-dev
    namespace: rollouts-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
